//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADACreator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConnectDevice()
        {
            this.TagInfoes = new HashSet<TagInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ConnectionType { get; set; }
        public string Destination { get; set; }
        public string S7PLCType { get; set; }
        public Nullable<int> S7PLCSlot { get; set; }
        public Nullable<int> S7PLCRack { get; set; }
        public Nullable<int> ModbusPort { get; set; }
        public byte ModbusDeviceId { get; set; }
        public string OPCUAUserName { get; set; }
        public string OPCUAUserPassword { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagInfo> TagInfoes { get; set; }
    }
}
