//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADACreator
{
    using System;
    using System.Collections.Generic;

    public partial class TagInfo
    {
        public TagInfo()
        {
            Type = TagType.eBool;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string MemoryAddress { get; set; }
        public string NodeId { get; set; }
        public int DeviceAttach { get; set; }
        public enum TagType
        {
            eBool,
            eByte,
            eShort,
            eInt,
            eReal,
            eDouble
        }
        public TagType Type { get; set; }
        public byte BitPosition { get; set; }
        public virtual ConnectDevice ConnectDevice { get; set; }
    }
}
